Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
c , f ,k :real


Inicio
escreval (" digite uma temperatura em celcius:")
leia (c)
 f <-(9 * c + 160) / 5
 escreval ("a temperatura em  fahrenheit é :", f)

Fimalgoritmo