Algoritmo "semnome"

Var
vet : vetor [1..14] de inteiro
pais : caracter
casos : vetor [1..14] de inteiro
n : inteiro
 mortes : vetor [1..14] de inteiro
 cont : inteiro
Inicio
 para cont de 1 ate 14 faca
 escreval ("digite os paises")
 leia (pais)
 escreval (" casos:")
 leia (casos[cont])
 escreval (" mortes: ")
 leia (mortes[cont])
 fimpara
 escreval ("digite um numero para pesquisar o país")
  leia (n)
  cont <- 1
  


Fimalgoritmo