Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/08/2020
Var
// Seção de Declarações das variáveis 
cont : inteiro
 r : inteiro
Inicio
para cont de 1 ate 1000 faca
r <- cont*7
escreval (r)

 fimpara
Fimalgoritmo