Algoritmo "semnome"

Var
nome : caracter
nome1 : caracter
altura : real
altura1 : real
Inicio
escreval ("digite seu nome:")
leia (nome)
escreval ("digite sua altura:")
leia (altura)
 escreval ("digite seu nome:")
leia (nome1)
escreval ("digite sua altura:")
leia (altura1)
se altura > altura1  entao
   escreva (nome, "é maior que ", nome1)
senao
   escreva (nome1, "é maior que ",nome)

fimse


Fimalgoritmo
