Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/08/2020
Var
c , f ,k :real


Inicio
escreval (" digite uma temperatura em  Fahrenheit:")
leia (f)
 c <- ((f-32)*5)/9
 escreval ("a temperatura em  celcius é :", c)

Fimalgoritmo